version: '3.8'

services:
  nginx:
    restart: always
    hostname: "${APP_NAME}_nginx"
    image: "${APP_NAME}_nginx"
    container_name: "${APP_NAME}_nginx"
    build:
      context: .
      dockerfile: ./environments/development/Dockerfile-nginx
    volumes:
      - ${APPLICATION}:/var/www/html
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    depends_on:
      - app
    networks:
      - app_network

  app:
    restart: always
    hostname: "${APP_NAME}_app"
    build:
      context: .
      dockerfile: ./environments/development/Dockerfile
      args:
        APP_DEBUG: ${APP_DEBUG}
    image: "${APP_NAME}_php"
    container_name: "app"
    ports:
      - ${FPM_PORT}:9000
    volumes:
      - '.:/var/www/html'
    networks:
      - app_network
    depends_on:
      - mysql

  mysql:
    restart: always
    hostname: "${APP_NAME}_mysql"
    image: "${APP_NAME}_mysql"
    container_name: "${APP_NAME}_mysql"
    build:
      context: .
      dockerfile: ./environments/development/Dockerfile-mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    ports:
      - ${DB_PORT}:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      app_network:
        aliases:
          - mysql

networks:
  app_network:
    driver: bridge
    name: ${APP_NAME}_network

volumes:
  database:
    driver: local
    name: ${APP_NAME}_db_vol
  rmqdata:
    name: ${APP_NAME}_rmq_vol
